data_ingestion:
  postgres:
    POSTGRES_USER: "airflow"
    POSTGRES_PASSWORD: "airflow"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    POSTGRES_DB: "airflow"
    POSTGRES_TABLE_NAME: "bank_churners"
  csv:
    data_path: "/opt/airflow/data/input/BankChurners_csv.csv"
    raw_data_path: "/opt/airflow/data/intermediate/raw_data.csv"
    preproc_data_path: "/opt/airflow/data/intermediate/preproc_data.csv"
    train_data_path: "/opt/airflow/data/intermediate/train.csv"
    test_data_path: "/opt/airflow/data/intermediate/test.csv"

data_validation:
  required_columns:
    - "clientnum"
    - "customer_age"
    - "dependent_count"
    - "months_on_book"
    - "total_relationship_count"
    - "months_inactive_12_mon"
    - "contacts_count_12_mon"
    - "credit_limit"
    - "total_revolving_bal"
    - "avg_open_to_buy"
    - "total_amt_chng_q4_q1"
    - "total_trans_amt"
    - "total_trans_ct"
    - "total_ct_chng_q4_q1"
    - "avg_utilization_ratio"
    - "naive_bayes_classifier_attrition_flag_card_category_contacts_count_12_mon_dependent_count_education_level_months_inactive_12_mon_1"
    - "naive_bayes_classifier_attrition_flag_card_category_contacts_count_12_mon_dependent_count_education_level_months_inactive_12_mon_2"
    - "churn_flag"
    - "gender"
    - "education_level"
    - "marital_status"
    - "income_category"
    - "card_category"
  
  report_save_path: "/opt/airflow/data/data_validation_report.csv"

preprocessing:
  paths:
    train_preprocessed_path: "/opt/airflow/data/feature_eng/train_feature_eng.csv"
    test_preprocessed_path: "/opt/airflow/data/feature_eng/test_feature_eng.csv"
    preprocessor_path: "/opt/airflow/model/preprocessor.gz"

  one_hot_encoding:
    columns:
      - "gender"
  
  ordinal_encoding:
    columns:
      education_level: 
       - "Uneducated"
       - "High School"
       - "College"
       - "Graduate"
       - "Post-Graduate"
       - "Doctorate"
       - "Unknown"
      
      income_category: 
        - "Less than $40K"
        - "$40K - $60K"
        - "$60K - $80K"
        - "$80K - $120K"
        - "$120K +"
        - "Unknown"
      
      card_category: 
        - "Blue"
        - "Silver"
        - "Gold"
        - "Platinum"
  
  target_encoding:
    columns:
      - "marital_status"
    
  to_drop:
    columns:
      - "naive_bayes_classifier_attrition_flag_card_category_contacts_count_12_mon_dependent_count_education_level_months_inactive_12_mon_1"
      - "naive_bayes_classifier_attrition_flag_card_category_contacts_count_12_mon_dependent_count_education_level_months_inactive_12_mon_2"
      - "clientnum"
      - "avg_open_to_buy"

model:
  save_path: "/opt/airflow/model/train_model.pkl"
  best_params:
    objective: "binary"
    metric: "roc_auc"
    n_estimators: 1000
    verbosity: -1
    bagging_freq: 1
    class_weight: "balanced" 
    learning_rate: 0.017535345166904838
    num_leaves: 942
    subsample: 0.8490611533540497
    colsample_bytree: 0.3775159533799494
    min_data_in_leaf: 90
  